export default [
  {
    id: 1,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 2,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 3,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 4,
    issuer: "",
    currency: "",
    type: "",
    rank: "",
    call: "",
    returnDay: "",
    cp: "",
    interestDay: "",
  }
]