export default [
  {
    id: 1,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 2,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 3,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 4,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 5,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 6,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 7,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 8,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 9,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 10,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 11,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 12,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 13,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 14,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 15,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 16,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 17,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
  {
    id: 18,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2027年7月19日",
    returnDay: "",
    cp: "6.875%",
    interestDay: "1月6日/7月6日",
  },
  {
    id: 19,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "永久劣後債",
    rank: "B2u/B+/NR",
    call: "2023年7月19日",
    returnDay: "",
    cp: "6.000%",
    interestDay: "1月19日/7月19日",
  },
  {
    id: 20,
    issuer: "ソフトバンクグループ",
    currency: "米ドル",
    type: "シニア債",
    rank: "Ba3u/BB+/NR",
    call: "",
    returnDay: "2024年9月19日",
    cp: "4.750%",
    interestDay: "3月19日/9月19日",
  },
];
